# web: redis-browser --config config/redis_browser.yml &
sidekiq: bundle exec sidekiq -C ./config/sidekiq.yml
web: rails s
#web: subcontract --rbenv . --chdir ../strings-server --signal INT -- bundle exec rackup config.ru -p $PORT &
