general: &general
  DOMAIN_NAME:          'api.dev.local'
  LOCALHOST:            '127.0.0.1:3000'
  IP:                   '127.0.0.1'
  ACCESS_TOKEN:         'fdd110671210f2be353995806414f9d8'
  RACK_CORS_ORIGINS:    'localhost:4200'
  REDIS_URL:            'redis://localhost:6379/0'
  REDIS_DATA:           'strings_data'
  REDIS_CACHE:          'redis://localhost:6379/0/strings_cache'
  REDIS_NAMESPACE:      'sidekiq'

rethinkdb: &rethinkdb
  RETHINKDB_DB:         'strings'
  RETHINKDB_URL:        'rethinkdb://localhost:28015/strings'
  RETHINKDB_HOST:       '127.0.0.1'
  RETHINKDB_PORT:       '28015'
  RETHINKDB_AUTH:       'rethinkdb://kapranov:9c838683-fa89-51fc-862c-9b423eb0c291@127.0.0.1:28015/strings'
  RETHINKDB_USER:       'kapranov'
  RETHINKDB_PASSWORD:   '9c838683-fa89-51fc-862c-9b423eb0c291'

admin: &admin
 ADMIN_FIRST_NAME:      'Oleg'
 ADMIN_LAST_NAME:       'Kapranov'
 ADMIN_MIDDLE_NAME:     'G.'
 ADMIN_EMAIL:           'lugatex@yahoo.com'
 ADMIN_PASSWORD:        '12345678'
 ADMIN_DESCRIPTION:     'Hello World!'

development:
  <<: *general
  <<: *rethinkdb
  <<: *admin
  SECRET_KEY_BASE:      '599ac15f824b962410dfc9748f4dabb442822d470ef62b6fbc0ba7123181daf55f579fe59fe862a4771ce211f8f79edda5b52e6458c0b35a1f15d1b2a8d28c67'

test:
  <<: *general
  <<: *rethinkdb
  <<: *admin
  SECRET_KEY_BASE:      'e8553de0c309a32e73a4852ea6886cc7ebc5a381e41f0c302637b9d78836ab03e7f2e72d15392c06b816e7f888ba538494e436f03d404ee2eca27a863a86651e'

production:
  <<: *general
  <<: *admin
  <<: *rethinkdb
  SECRET_KEY_BASE:      '9e61e86f559feea526dc08c210d14dd890cca699c414a4b686d352ade7c8708b895c3f5a2f921cbe2ffe3e5b11028a93d031b77dc8400dd67a91460f413064dd'
