general: &general
  PORT:               '3000'
  CORS:               '127.0.0.1:3000'
  LOCALHOST:          '127.0.0.1'
  DOMAIN_NAME:        'api.dev.local'
  RACK_CORS_ORIGINS:  'localhost:4200'

redis: &redis
  REDIS_URL:          'redis://localhost:6379/0'
  REDIS_DATA:         'strings_data'
  REDIS_CACHE:        'redis://localhost:6379/0/strings_cache'
  REDIS_NAMESPACE:    'sidekiq'

rethinkdb: &rethinkdb
  RETHINKDB_DB:       'jwtdemo'
  RETHINKDB_URL:      'rethinkdb://localhost:28015/jwtdemo'
  RETHINKDB_HOST:     '127.0.0.1'
  RETHINKDB_PORT:     '28015'
  RETHINKDB_AUTH:     'rethinkdb://kapranov:9c838683-fa89-51fc-862c-9b423eb0c291@127.0.0.1:28015/jwtdemo'
  RETHINKDB_USER:     'kapranov'
  RETHINKDB_PASSWORD: '9c838683-fa89-51fc-862c-9b423eb0c291'

admin: &admin
  ADMIN_FIRST_NAME:   'Oleg'
  ADMIN_LAST_NAME:    'Kapranov'
  ADMIN_MIDDLE_NAME:  'G.'
  ADMIN_EMAIL:        'lugatex@yahoo.com'
  ADMIN_PASSWORD:     '12345678'
  ADMIN_DESCRIPTION:  'Hello World!'
  ADMIN_PHONE_CELL:   '380997170609'
  ADMIN_PHONE_WORK:   '380997170609'
  ADMIN_PHONE_HOME:   '380965468967'

token: &token
  TOKEN_ACCESS:       'fdd110671210f2be353995806414f9d8'
  TOKEN_USERNAME:     'Oleg.G.Kapranov'
  TOKEN_PASSWORD:     '87654321'

development:
  <<: *general
  <<: *redis
  <<: *rethinkdb
  <<: *admin
  <<: *token
  AUTH_SECRET:        'somethingrandomrandom'
  SECRET_KEY_BASE:    '1d12e5dc037039e25692fb012c580c9baf06325319c4404f43fdd48b3eea7e3bed34d290ae703446e5d1579cdb6704304e5d307e17cacfc9f33379323548d101'

test:
  <<: *general
  <<: *redis
  <<: *rethinkdb
  <<: *admin
  <<: *token
  AUTH_SECRET:        '\x85\x11\xFA\xEF\xF2A\x11\xC7\x90\x9C!{\xDC\x11W\xFB\x93\xE5\xA3\xCD\xE3\xC2\x9E#7\xC4\xCDa\xCF\xC9/\xEA'
  SECRET_KEY_BASE:    '69dedff27eb3349dd0ea880280aa6910b96901c33adb96e1165a4186edb328c35df50089581fb1e3340602a76939aa87ecccdbacd175afbd10313f48f23bd021'

production:
  <<: *general
  <<: *redis
  <<: *rethinkdb
  <<: *admin
  <<: *token
  SECRET_KEY_BASE:    'eeb0a8a1fbcf5898a7623448abfe3e5f9722eff327bfb7b60246e84775fb2dc2eab449cae224d8547c0fddee6a8ef8df9a20b24415d8a5660ce0e6a3cfabe61a'
