general: &general
  port:                   <%= ENV["PORT"] %>
  host_ip:                <%= ENV["HOST_IP"] %>
  localhost:              <%= ENV["LOCALHOST"] %>
  domain_name:            <%= ENV["DOMAIN_NAME"] %>
  rack_cors_origins:      <%= ENV["RACK_CORS_ORIGINS"] %>
  default_email_reply:    <%= ENV["DEFAULT_EMAIL_REPLY"] %>
  access_token:           <%= ENV["ACCESS_TOKEN"] %>
  redis_url:              <%= ENV["REDIS_URL"] %>
  secret_key_base:        <%= ENV["SECRET_KEY_BASE"] %>

admin: &admin
 admin_first_name:        <%= ENV["ADMIN_FIRST_NAME"] %>
 admin_last_name:         <%= ENV["ADMIN_LAST_NAME"] %>
 admin_middle_name:       <%= ENV["ADMIN_MIDDLE_NAME"] %>
 admin_email:             <%= ENV["ADMIN_EMAIL"] %>
 admin_password:          <%= ENV["ADMIN_PASSWORD"] %>
 admin_description:       <%= ENV["ADMIN_DESCRIPTION"] %>

mail: &mail
 email_username:          <%= ENV["EMAIL_USERNAME"] %>
 email_password:          <%= ENV["EMAIL_PASSWORD"] %>

rethinkdb: &rethinkdb
  rethinkdb_db:           <%= ENV["RETHINKDB_DB"] %>
  rethinkdb_url:          <%= ENV["RETHINKDB_URL"] %>
  rethinkdb_host:         <%= ENV["RETHINKDB_HOST"] %>
  rethinkdb_port:         <%= ENV["RETHINKDB_PORT"] %>
  rethinkdb_auth:         <%= ENV["RETHINKDB_AUTH"] %>
  rethinkdb_user:         <%= ENV["RETHINKDB_USER"] %>
  rethinkdb_password:     <%= ENV["RETHINKDB_PASSWORD"] %>

development:
  <<: *general
  <<: *rethinkdb
  <<: *admin
  <<: *mail

test:
  <<: *general
  <<: *rethinkdb
  <<: *admin
  <<: *mail

production:
  <<: *general
  <<: *rethinkdb
  <<: *admin
  <<: *mail
