development:
  localhost:          <%= ENV["LOCALHOST"] %>
  rack_cors_origins:  <%= ENV["RACK_CORS_ORIGINS"] %>
  access_token:       <%= ENV["ACCESS_TOKEN"] %>
  secret_key_base:    <%= ENV["SECRET_KEY_BASE"] %>
  redis_url:          <%= ENV["REDIS_URL"] %>
test:
  access_token:       <%= ENV["ACCESS_TOKEN"] %>
  secret_key_base:    <%= ENV["SECRET_KEY_BASE"] %>

production:
  access_token:       <%= ENV["ACCESS_TOKEN"] %>
  secret_key_base:    <%= ENV["SECRET_KEY_BASE"] %>
