general: &general
  cors:                 <%= ENV["CORS"] %>
  port:                 <%= ENV["PORT"] %>
  localhost:            <%= ENV["LOCALHOST"] %>
  domain_name:          <%= ENV["DOMAIN_NAME"] %>
  secret_key_base:      <%= ENV["SECRET_KEY_BASE"] %>
  rack_cors_origins:    <%= ENV["RACK_CORS_ORIGINS"] %>

redis: &redis
  redis_url:            <%= ENV["REDIS_URL"] %>
  redis_data:           <%= ENV["REDIS_DATA"] %>
  redis_cache:          <%= ENV["REDIS_CACHE"] %>
  redis_namespace:      <%= ENV["REDIS_NAMESPACE"] %>

rethinkdb: &rethinkdb
  rethinkdb_db:         <%= ENV["RETHINKDB_DB"] %>
  rethinkdb_url:        <%= ENV["RETHINKDB_URL"] %>
  rethinkdb_host:       <%= ENV["RETHINKDB_HOST"] %>
  rethinkdb_port:       <%= ENV["RETHINKDB_PORT"] %>
  rethinkdb_auth:       <%= ENV["RETHINKDB_AUTH"] %>
  rethinkdb_user:       <%= ENV["RETHINKDB_USER"] %>
  rethinkdb_password:   <%= ENV["RETHINKDB_PASSWORD"] %>

admin: &admin
  admin_first_name:     <%= ENV["ADMIN_FIRST_NAME"] %>
  admin_last_name:      <%= ENV["ADMIN_LAST_NAME"] %>
  admin_middle_name:    <%= ENV["ADMIN_MIDDLE_NAME"] %>
  admin_email:          <%= ENV["ADMIN_EMAIL"] %>
  admin_password:       <%= ENV["ADMIN_PASSWORD"] %>
  admin_description:    <%= ENV["ADMIN_DESCRIPTION"] %>
  admin_phone_cell:     <%= ENV["ADMIN_PHONE_CELL"] %>
  admin_phone_work:     <%= ENV["ADMIN_PHONE_WORK"] %>
  admin_phone_home:     <%= ENV["ADMIN_PHONE_HOME"] %>

token: &token
  token_access:         <%= ENV["TOKEN_ACCESS"] %>
  token_username:       <%= ENV["TOKEN_USERNAME"] %>
  token_password:       <%= ENV["TOKEN_PASSWORD"] %>

development:
  <<: *general
  <<: *redis
  <<: *rethinkdb
  <<: *admin
  <<: *token

test:
  <<: *general
  <<: *redis
  <<: *rethinkdb
  <<: *admin
  <<: *token

production:
  <<: *general
  <<: *redis
  <<: *rethinkdb
  <<: *admin
  <<: *token
