general: &general
  localhost:          <%= ENV["LOCALHOST"] %>
  host_ip:            <%= ENV["HOST_IP"] %>
  rack_cors_origins:  <%= ENV["RACK_CORS_ORIGINS"] %>
  access_token:       <%= ENV["ACCESS_TOKEN"] %>
  secret_key_base:    <%= ENV["SECRET_KEY_BASE"] %>


rethinkdb: &rethinkdb
  rethinkdb_db:       <%= ENV["RETHINKDB_DB"] %>
  rethinkdb_url:      <%= ENV["RETHINKDB_URL"] %>
  rethinkdb_host:     <%= ENV["RETHINKDB_HOST"] %>
  rethinkdb_port:     <%= ENV["RETHINKDB_PORT"] %>
  rethinkdb_auth:     <%= ENV["RETHINKDB_AUTH"] %>
  rethinkdb_user:     <%= ENV["RETHINKDB_USER"] %>
  rethinkdb_password: <%= ENV["RETHINKDB_PASSWORD"] %>

redis: &redis
  redis_url:          <%= ENV["REDIS_URL"] %>

development:
  <<: *general
  <<: redis
  <<: *rethinkdb

test:
  <<: *general
  <<: redis
  <<: *rethinkdb

production:
  <<: *general
  <<: redis
  <<: *rethinkdb
