source 'https://rubygems.org'

ruby '2.3.3'

gem 'sinatra',            '~> 1.4'
gem 'sinatra-contrib',    '~> 1.4'
gem 'dm-core',            '~> 1.2'
gem 'dm-sqlite-adapter',  '~> 1.2'
gem 'dm-validations',     '~> 1.2'
gem 'dm-timestamps',      '~> 1.2'
gem 'dm-migrations',      '~> 1.2'

group :development, :test do
  gem 'timecop'
  gem 'simplecov'
  gem 'minitest'
end
